# Generated by Django 4.0.7 on 2023-05-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_profile_id_alter_relationship_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_depressed',
            field=models.BooleanField(default=False),
        ),
    ]
