# Generated by Django 4.0.7 on 2023-04-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20210201_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.IntegerField(choices=[(1, 'Like'), (2, 'Follow'), (3, 'Comment'), (4, 'Reply'), (5, 'Like-Comment'), (6, 'Like-Reply'), (7, 'Relative')]),
        ),
    ]
