# Generated by Django 4.0.7 on 2023-05-19 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_chat_is_depressed_alter_chat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='is_depressed',
        ),
    ]
