# Generated by Django 4.0.7 on 2023-05-20 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_depressedmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='depressedmessage',
            name='is_depressed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='depressedmessage',
            name='text',
            field=models.TextField(),
        ),
    ]
